parameters:
  project_url: https://github.com/schulit/portal

common:
  app:
    url: "%env(APP_URL)%"
    name: "%env(APP_NAME)%"
    version: "%version%"
    project_url: ~
    logo: "%env(APP_LOGO)%"
    small_logo: "%env(APP_SMALLLOGO)%"
  locales: "%locales%"
  menu: mainMenu
  disable:
    mail: true
