security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        backend_users:
            entity:
                class: App\Entity\User
                property: idpId

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        dependencies:
            pattern: ^/dependencies
            security: false

        login:
            security: false
            pattern: ^/admin/saml/(login|discovery|metadata.xml)$

        logout:
            security: false
            pattern: ^/admin/logout/success

        auth:
            security: false
            pattern: ^/admin/auth

        backend:
            pattern: ^/admin
            provider: backend_users
            saml:
                provider: backend_users
                user_creator: App\Security\User\UserCreator
                login_path: /admin/saml/login
                check_path: /admin/saml/login_check
                attribute_mapper: App\Security\User\AttributeMapper
                failure_path: /auth/error
            logout:
                path: /admin/logout
                target: /admin/logout/success


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin/saml/(login|discovery|metadata.xml)$, roles: IS_ANONYMOUS }
        - { path: ^/admin/logout/success$, roles: IS_ANONYMOUS }
        - { path: ^/admin, roles: ROLE_ADMIN }
