#index:
#    path: /
#    controller: App\Controller\DefaultController::index

lightsaml_sp:
  resource: "@LightSamlSpBundle/Resources/config/routing.yml"
  prefix: admin/saml

composer:
  resource: "@ComposerDependencyListBundle/Controller"
  type: annotation
  prefix: /dependencies

logout:
  path: /admin/logout