controllers:
  resource: ../src/Controller/
  type: attribute

lightsaml_sp:
  resource: "@LightSamlSpBundle/Resources/config/routing.yml"
  prefix: admin/saml

composer:
  resource: "@ComposerDependencyListBundle/Controller"
  type: annotation
  prefix: /dependencies

logout:
  path: /admin/logout

logout_success:
  path: /admin/logout/success
  defaults: { _controller: SchulIT\CommonBundle\Controller\LogoutController::logout }